In [4]:
import pandas as pd

df = pd.read_csv('cities.csv')
df.head()

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State"""
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI

## 4) Perform describe and info on dataframe

In [5]:
df.describe()

             LatD      "LatM"      "LatS"      "LonD"      "LonM"      "LonS"
count  128.000000  128.000000  128.000000  128.000000  128.000000  128.000000
mean    38.820312   30.765625   27.492188   93.250000   27.742188   26.960938
std      5.200596   16.426158   18.977814   15.466499   16.927937   18.727807
min     26.000000    1.000000    0.000000   71.000000    0.000000    0.000000
25%     35.000000   16.000000   11.000000   80.000000   14.000000   11.000000
50%     39.000000   31.000000   24.000000   89.500000   26.500000   23.500000
75%     42.250000   45.000000   47.000000  103.250000   40.250000   47.000000
max     50.000000   59.000000   59.000000  123.000000   58.000000   59.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LatD      128 non-null    int64
 1    "LatM"   128 non-null    int64
 2    "LatS"   128 non-null    int64
 3    "NS"     128 non-null    object
 4    "LonD"   128 non-null    int64
 5    "LonM"   128 non-null    int64
 6    "LonS"   128 non-null    int64
 7    "EW"     128 non-null    object
 8    "City"   128 non-null    object
 9    "State"  128 non-null    object
dtypes: int64(6), object(4)
memory usage: 10.1+ KB

## 5) Export and save this data as cities1.csv

In [8]:
df.to_csv('cities1.csv')

## 2) Import xlsx in a dataframe

In [10]:
!pip install openpyxl

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/6a/94/a59521de836ef0da54aaf50da6c4da8fb4072fb3053fa71f052fd9399e7a/openpyxl-3.1.2-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
   ------------------ --------------------- 112.6/250.0 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 250.0/250.0 kB 2.6 MB/s eta 0:00:00
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
car_sales = pd.read_excel('CarSalesByModelStart.xlsx')
car_sales.head()

,Year,Month,Date,Model,Dealer ID,Quantity Sold,Profit
0,2018,January,2018-01-01 23:00:00,Beaufort,1222,10,15000.0
1,2018,January,2018-01-01 23:00:00,Salish,1222,13,39650.0
2,2018,January,2018-01-01 23:00:00,Labrador,1222,16,12800.0
3,2018,January,2018-01-01 23:00:00,Champlain,1222,3,6900.0
4,2018,January,2018-01-01 23:00:00,Hudson,1222,22,11000.0

## 4) Perform describe and info on dataframe

In [13]:
car_sales.describe()

,Year,Date,Dealer ID,Quantity Sold,Profit
count,1200.000000,1200,1200.000000,1200.00000,1200.000000
mean,2018.500000,2018-12-16 23:00:00,1281.800000,17.99750,24974.055208
min,2018.000000,2018-01-01 23:00:00,1212.000000,2.00000,4600.000000
25%,2018.000000,2018-06-24 11:00:00,1217.000000,11.00000,13500.000000
50%,2018.500000,2018-12-17 11:00:00,1256.000000,18.00000,18500.000000
75%,2019.000000,2019-06-09 11:00:00,1336.000000,24.00000,28922.812500
max,2019.000000,2019-12-01 23:00:00,1402.000000,48.00000,83875.000000
std,0.500208,NaN,72.453672,9.97432,17370.750612

In [14]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           1200 non-null   int64
 1   Month          1200 non-null   object
 2   Date           1200 non-null   datetime64[ns]
 3   Model          1200 non-null   object
 4   Dealer ID      1200 non-null   int64
 5   Quantity Sold  1200 non-null   int64
 6   Profit         1200 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 65.8+ KB

## 5) Export and save this data as CarSalesByModelStart1.xlsx

In [16]:
car_sales.to_excel('CarSalesByModelStart1.xlsx')

## 1) Download Jay.json in C7W1 Activity folder
## 2) Import the Json in dataframe
## 3) Add a column to the dataframe
## 4) Perform describe and info on dataframe
## 5) Export and save this data as Jay1.jso

In [18]:
jay_data = pd.read_json('Jay (1).json')

In [19]:
jay_data.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.800000
std     42.299949   14.510259   16.450434   266.377134
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [20]:
jay_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.6 KB

In [21]:
jay_data.to_json('Jay (1)1.json')